# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  helpdesksystem-web:
    image: helpdesksystem-web
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4200:80
